In [1]:
import numpy as np
import pandas as pd

In [2]:
data = pd.read_csv('/content/spending_patterns_detailed.csv')

In [5]:
data.sample(5)

,Customer ID,Category,Item,Quantity,Price Per Unit,Total Spent,Payment Method,Location,Transaction Date
8952,CUST_0142,Personal Hygiene,Shampoo,4,13.09,52.34,Debit Card,Online,2024-05-05
3840,CUST_0109,Gifts,Flowers,5,27.47,137.34,Debit Card,In-store,2023-01-23
6619,CUST_0165,Housing and Utilities,Gas Bill,1,126.34,126.34,Debit Card,Online,2024-10-18
1576,CUST_0053,Hobbies,Books,1,5.23,5.23,Debit Card,In-store,2024-03-18
1418,CUST_0117,Transportation,Gas,1,88.73,88.73,Debit Card,Online,2023-12-12

#Q-3 --Compare spending in "Electronics" vs. "Clothing"

In [9]:
# we will get this in the items colm
# so get the unique items from the colm
data['Item'].unique()

array(['Milk', 'Dinner with Friends', 'Water Bill', 'Yoga Class',
       'Flowers', 'Car Repair', 'Personal Trainer', 'Plane Ticket',
       'Kids Games', 'Bread', 'Toothpaste', 'Crochet Supplies',
       'Gas Bill', 'Jewelry', 'Car', 'Shoes', 'Dentist Visit', 'Chicken',
       'Clothes', 'Snacks', 'Fast Food', 'Restaurant Meal', 'Taxi/Uber',
       'Doctor Visit', 'Public Transit', 'Medicine', 'Vegetables', 'Gas',
       'Streaming Service', 'Shampoo', 'Electricity Bill',
       'Skin Care Products', 'Coffee', 'Art Supplies', 'Magazine',
       'Movie Tickets', 'Workout Equipment', 'Meat', 'Rent',
       'Concert Tickets', 'Gift Cards', 'Hotel Stay', 'Soap', 'Books',
       'Electronics', 'Fruits', 'Gym Membership', 'Video Games'],
      dtype=object)

In [17]:
# we have to compare the both the spending
# we will have to apply the grroupby
# so we will seperate the electronics and the cloting
data['Item'].isin(['Electronics' , 'Cloths']) # this will give the boolean values
# this will give the data of the table which only have that items
# now  from the boolean we will convert it to the true data
data[data['Item'].isin(['Electronics' , 'Clothes'])]

# now we will groupby it on basis of the item
data[data['Item'].isin(['Electronics' , 'Clothes'])].groupby('Item')
# now we will find the total spent on basis of the items and then find the avg total spent
data[data['Item'].isin(['Electronics' , 'Clothes'])].groupby('Item')['Total Spent'].mean()

Item
Clothes         255.630703
Electronics    2419.965245
Name: Total Spent, dtype: float64

#What percentage of customers have made purchases in at least 5 different categories?

In [30]:
# we will find the groupby on basis of the customers and then find the category
data.groupby('Customer ID')
# on basis of the customer id we will find the category
# nunique so we will find the number
cat_count= data.groupby('Customer ID')['Category'].nunique()
#this will give the uniwue category in whcih shopping have been done by the cutomer

In [33]:
# we will now find where the cat count > 5
cat_count[cat_count>5]
# and we need the count
cat_count[cat_count>5].count()

# find the precentage
cat_count[cat_count>5].count()/ data['Customer ID'].nunique()
# so the 100% of the data

np.float64(1.0)

# now compare the sales of the jan of the one year vs jan of the another yr

In [34]:
data.sample(5)

,Customer ID,Category,Item,Quantity,Price Per Unit,Total Spent,Payment Method,Location,Transaction Date
8666,CUST_0194,Gifts,Jewelry,3,169.04,507.13,Credit Card,Mobile App,2023-09-05
401,CUST_0170,Groceries,Milk,1,4.16,4.16,Debit Card,Online,2024-02-22
1220,CUST_0133,Medical/Dental,Dentist Visit,1,473.26,473.26,Credit Card,In-store,2024-04-30
3839,CUST_0106,Medical/Dental,Medicine,1,686.20,686.20,Credit Card,In-store,2025-01-11
2787,CUST_0052,Medical/Dental,Medicine,1,307.36,307.36,Debit Card,Mobile App,2023-06-18

In [37]:
# now from the data we will only find the year
data['Transaction Date']= pd.to_datetime(data['Transaction Date'])

In [39]:
data # it is now converted to the date and time

,Customer ID,Category,Item,Quantity,Price Per Unit,Total Spent,Payment Method,Location,Transaction Date
0,CUST_0159,Groceries,Milk,1,1.28,1.28,Debit Card,Mobile App,2024-11-13
1,CUST_0017,Friend Activities,Dinner with Friends,2,74.69,149.39,Debit Card,In-store,2023-05-04
2,CUST_0094,Housing and Utilities,Water Bill,1,76.06,76.06,Digital Wallet,Mobile App,2023-12-16
3,CUST_0162,Fitness,Yoga Class,5,11.24,56.18,Cash,In-store,2024-01-28
4,CUST_0129,Gifts,Flowers,3,43.71,131.12,Debit Card,In-store,2023-07-28
...,...,...,...,...,...,...,...,...,...
9995,CUST_0072,Housing and Utilities,Water Bill,1,69.46,69.46,Debit Card,Online,2023-09-01
9996,CUST_0150,Groceries,Snacks,5,15.54,77.70,Debit Card,In-store,2024-06-27
9997,CUST_0122,Shopping,Electronics,1,732.03,732.03,Debit Card,In-store,2024-03-19
9998,CUST_0133,Transportation,Car Repair,1,107.63,107.63,Debit Card,Mobile App,2024-10-17
9999,CUST_0058,Housing and Utilities,Gas Bill,1,98.79,98.79,Credit Card,Mobile App,2024-08-04

In [42]:
# but the functiion we have it can  give the month or the year but we need the both
# so we can do the following we can create 2 colm   for the month and the year
data['Month'] = data['Transaction Date'].dt.month

In [58]:
#now we will crete a new colm on the bsaed on the year
data['year'] = data['Transaction Date'].dt.year

In [59]:
# NOW we will creta a new colm by adding the bboth
# now first convert the month and the theyear to the object type
data['Month'].  astype("object")
data['year'].astype("object")
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 12 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Customer ID       10000 non-null  object
 1   Category          10000 non-null  object
 2   Item              10000 non-null  object
 3   Quantity          10000 non-null  int64
 4   Price Per Unit    10000 non-null  float64
 5   Total Spent       10000 non-null  float64
 6   Payment Method    10000 non-null  object
 7   Location          10000 non-null  object
 8   Transaction Date  10000 non-null  datetime64[ns]
 9   year              10000 non-null  int32
 10  Month             10000 non-null  int32
 11  Month year        10000 non-null  object
dtypes: datetime64[ns](1), float64(2), int32(2), int64(1), object(6)
memory usage: 859.5+ KB

In [60]:
# check the infor
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 12 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Customer ID       10000 non-null  object
 1   Category          10000 non-null  object
 2   Item              10000 non-null  object
 3   Quantity          10000 non-null  int64
 4   Price Per Unit    10000 non-null  float64
 5   Total Spent       10000 non-null  float64
 6   Payment Method    10000 non-null  object
 7   Location          10000 non-null  object
 8   Transaction Date  10000 non-null  datetime64[ns]
 9   year              10000 non-null  int32
 10  Month             10000 non-null  int32
 11  Month year        10000 non-null  object
dtypes: datetime64[ns](1), float64(2), int32(2), int64(1), object(6)
memory usage: 859.5+ KB

In [63]:
# now create  a new colm
data['Month year'] = data['Month'].astype('str')+"-"+data['year'].astype("str")

In [64]:
data

,Customer ID,Category,Item,Quantity,Price Per Unit,Total Spent,Payment Method,Location,Transaction Date,year,Month,Month year
0,CUST_0159,Groceries,Milk,1,1.28,1.28,Debit Card,Mobile App,2024-11-13,2024,11,11-2024
1,CUST_0017,Friend Activities,Dinner with Friends,2,74.69,149.39,Debit Card,In-store,2023-05-04,2023,5,5-2023
2,CUST_0094,Housing and Utilities,Water Bill,1,76.06,76.06,Digital Wallet,Mobile App,2023-12-16,2023,12,12-2023
3,CUST_0162,Fitness,Yoga Class,5,11.24,56.18,Cash,In-store,2024-01-28,2024,1,1-2024
4,CUST_0129,Gifts,Flowers,3,43.71,131.12,Debit Card,In-store,2023-07-28,2023,7,7-2023
...,...,...,...,...,...,...,...,...,...,...,...,...
9995,CUST_0072,Housing and Utilities,Water Bill,1,69.46,69.46,Debit Card,Online,2023-09-01,2023,9,9-2023
9996,CUST_0150,Groceries,Snacks,5,15.54,77.70,Debit Card,In-store,2024-06-27,2024,6,6-2024
9997,CUST_0122,Shopping,Electronics,1,732.03,732.03,Debit Card,In-store,2024-03-19,2024,3,3-2024
9998,CUST_0133,Transportation,Car Repair,1,107.63,107.63,Debit Card,Mobile App,2024-10-17,2024,10,10-2024
9999,CUST_0058,Housing and Utilities,Gas Bill,1,98.79,98.79,Credit Card,Mobile App,2024-08-04,2024,8,8-2024

In [65]:
data['Month year']

0       11-2024
1        5-2023
2       12-2023
3        1-2024
4        7-2023
         ...
9995     9-2023
9996     6-2024
9997     3-2024
9998    10-2024
9999     8-2024
Name: Month year, Length: 10000, dtype: object

In [68]:
# now on the basis of the month we can groupby the sales
data[(data['Transaction Date'].dt.year == 2024) & (data['Transaction Date'].dt.month>6)].shape[0]

2455